use_frameworks!

platform :ios, '10.0'

target 'LVBusiModule_Example' do
  pod 'LVBusiModule', :path => '../'

  target 'LVBusiModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
